### ISSUE TITLE
New release please?

### ISSUE THREAD

**Issue by stapelberg** [pretix/pretix-saferpay#4]
Hey

I’m interested in setting up TWINT via Saferpay, which I see was added recently.

The last release on PyPI seems to be from 2019, and I don’t see TWINT in the list of payment providers after installing `pretix-saferpay`.

Could you push a new release to PyPI please?

**Comment by raphaelm** [comment]
Pushed out 1.3.0 :)

**Comment by stapelberg** [comment]
Thanks, I can confirm that I see TWINT in the list of payment providers now :)
